name = "LogoPlots"
uuid = "463a02c6-07a9-4108-b146-0900016c928a"
authors = ["Benjamin Doran"]
version = "0.1.0-DEV"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
RecipesBase = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
